from .connection import get_cursor, get_connection, put_connection
from .models import init_db, migrate
from .dao import (
    upsert_poc_template,
    get_poc_template,
    create_scan_task,
    complete_scan_task,
    insert_discovered_assets,
    get_assets_by_task,
    insert_scan_results,
    get_scan_results_by_task,
    insert_host_results,
    insert_icp_results,
    get_cached_assets,
    set_cached_assets,
    clean_expired_cache,
    rebuild_dedup_index,
    insert_dedup_entry,
    load_dedup_index,
    upsert_checkpoint,
    load_checkpoint_from_db,
    upsert_template_coverage,
    upsert_template_icp_stats,
    refresh_materialized_views,
    get_db_stats,
    insert_scan_log,
    get_scan_logs,
    get_scan_logs_since,
    update_task_current_step,
)
